ee on table experiments (teleop and recreation script)
ShuoZheLi/air_hockey_challenge_robosuite pull request #1
Opened 2024-04-05 01:24 UTC by Sarcovora

ee_on_table includes the latest teleop and recreation scripts.

2024-04-05 01:28 UTC, michaelmunje commented on wandb/run-20240219_153826-mk7wdevu/files/diff.patch
Probably need to add wandb to .gitignore

2024-04-05 01:59 UTC, Sarcovora commented
made the recreation script realtime and added a few things to the gitignore.

2024-04-05 01:59 UTC, Sarcovora commented on wandb/run-20240219_153826-mk7wdevu/files/diff.patch
Just did this as well as adding the Datasets/ folder as well.

2024-04-08 22:53 UTC, michaelmunje requested changes

2024-04-08 22:53 UTC, michaelmunje commented on dataset.npy
Remove

2024-04-08 22:53 UTC, michaelmunje commented on datasetExamine.py
> +        data = np.load(f'./Datasets/{filename}')
Should be given in a script

2024-04-08 22:53 UTC, michaelmunje commented on datasetExamine.py
Put this in scripts/utils folder

2024-04-08 22:53 UTC, michaelmunje commented on foxglove_logging.py
Put in utils folder, at top of file, write what it is used for and any other details that will be relevant when reading it

2024-04-08 22:53 UTC, michaelmunje commented on ppo_continuous_action.py
Remove file

2024-04-08 22:53 UTC, michaelmunje commented on recreate_scene.py
> +data = np.load('./Datasets/dataset_46_1000_04042024203621.npy')
This should be a parameter

2024-04-08 22:53 UTC, michaelmunje commented on robosuite/controllers/osc.py
> +from robosuite.controllers.interpolators.linear_interpolator import LinearInterpolator
remove, dont need it here

2024-04-08 22:53 UTC, michaelmunje commented on robosuite/controllers/osc.py
> +        self.table_tilt = 0.09
Needs to be a parameter in the config

2024-04-08 22:53 UTC, michaelmunje commented on robosuite/controllers/osc.py
> +        self.position_limits = np.array([[0.15,-0.44,-10],[0.43,0.44,10]])
Should be in config/ a parameter

2024-04-08 22:53 UTC, michaelmunje commented on robosuite/controllers/osc.py
> +        self.fixed_ori = trans.euler2mat(np.array([0, math.pi - 0.0959931, 0]))
Should be a parameter / config

2024-04-08 22:53 UTC, michaelmunje commented on robosuite/controllers/osc.py
> +        self.transform_z = lambda x: self.table_tilt * (x - self.table_x_start) + self.table_elevation - self.z_offset
make it a function

2024-04-08 22:53 UTC, michaelmunje commented on robosuite/controllers/osc.py
This file should be a subclass of OSC since we modified it heavily. Specialized for our air hockey tasks on a tilted table

2024-04-08 22:53 UTC, michaelmunje commented on robosuite/environments/manipulation/air_hockey.py
> +        initial_qpos=[-0.5, -1.2, 1.376, -3.14, -1.420, -2.122],
Check if this actually works -- need to debug further
Hardcoded, should be a parameter.

2024-04-08 22:53 UTC, michaelmunje commented on robosuite/environments/manipulation/air_hockey.py
> +        initial_qpos =  (math.pi / 180 * np.array([-11.4, -63.2, 82.1, -113.2, -88.92, -101.25]))
Remove whichever one isn't needed.

2024-04-09 23:50 UTC, Sarthak-Dayal commented on dataset.npy
Deleted

2024-04-09 23:50 UTC, Sarthak-Dayal commented on wandb/run-20240219_153826-mk7wdevu/files/diff.patch
Resolving comment since we finished this

2024-04-10 00:03 UTC, Sarthak-Dayal commented on datasetExamine.py
> +        data = np.load(f'./Datasets/{filename}')
Updated to a script, including CLI args

2024-04-10 00:03 UTC, Sarthak-Dayal commented on datasetExamine.py
Moved to utils

2024-04-10 00:06 UTC, Sarthak-Dayal commented on ppo_continuous_action.py
Removed file, updated version on tasks branch

2024-04-10 00:14 UTC, Sarthak-Dayal commented on recreate_scene.py
> +data = np.load('./Datasets/dataset_46_1000_04042024203621.npy')
Turned into parameter and updated to script

2024-04-11 16:52 UTC, Sarthak-Dayal commented
Changes on this branch should be complete minus the validation and foxglove scripts

2024-04-16 01:55 UTC, michaelmunje approved these changes

2024-04-17 21:36 UTC, merged

2024-04-17 21:36 UTC, Sarthak-Dayal commented
Merging branch. Will delete after some testing.